export interface TagDefinition {
  slug: string;
  label: string;
  color: string;
  keywords: string[];
}

export const TAG_DEFINITIONS: TagDefinition[] = [
  {
    slug: "ai",
    label: "AI",
    color: "#8B5CF6",
    keywords: [
      "artificial intelligence",
      "machine learning",
      "deep learning",
      "ChatGPT",
      "OpenAI",
      "large language model",
      "LLM",
      "generative ai",
      "neural network",
      "GPT",
      "Claude",
      "Gemini",
      "copilot",
    ],
  },
  {
    slug: "climate",
    label: "Climate",
    color: "#059669",
    keywords: [
      "climate change",
      "global warming",
      "carbon emissions",
      "renewable energy",
      "fossil fuel",
      "greenhouse gas",
      "net zero",
      "climate crisis",
      "sustainability",
    ],
  },
  {
    slug: "crypto",
    label: "Crypto",
    color: "#F59E0B",
    keywords: [
      "cryptocurrency",
      "bitcoin",
      "ethereum",
      "blockchain",
      "crypto",
      "defi",
      "NFT",
      "web3",
      "stablecoin",
    ],
  },
  {
    slug: "cybersecurity",
    label: "Cybersecurity",
    color: "#EF4444",
    keywords: [
      "cybersecurity",
      "data breach",
      "ransomware",
      "malware",
      "phishing",
      "hacking",
      "zero-day",
      "vulnerability",
      "cyber attack",
    ],
  },
  {
    slug: "space",
    label: "Space",
    color: "#3B82F6",
    keywords: [
      "NASA",
      "SpaceX",
      "satellite",
      "astronaut",
      "Mars",
      "lunar",
      "orbit",
      "rocket launch",
      "space station",
      "James Webb",
    ],
  },
  {
    slug: "election",
    label: "Election",
    color: "#DC2626",
    keywords: [
      "election",
      "voting",
      "ballot",
      "campaign",
      "candidate",
      "polling",
      "midterm",
      "presidential race",
      "electoral",
    ],
  },
  {
    slug: "economy",
    label: "Economy",
    color: "#0891B2",
    keywords: [
      "inflation",
      "recession",
      "interest rate",
      "federal reserve",
      "GDP",
      "unemployment",
      "stock market",
      "economic growth",
      "trade deficit",
      "tariff",
      "trade war",
      "layoffs",
      "IPO",
      "Wall Street",
      "central bank",
    ],
  },
  {
    slug: "health-crisis",
    label: "Health Crisis",
    color: "#E11D48",
    keywords: [
      "pandemic",
      "epidemic",
      "outbreak",
      "public health emergency",
      "bird flu",
      "WHO",
      "vaccine mandate",
      "quarantine",
    ],
  },
  {
    slug: "evs",
    label: "EVs",
    color: "#10B981",
    keywords: [
      "electric vehicle",
      "EV",
      "Tesla",
      "charging station",
      "battery technology",
      "hybrid vehicle",
      "electric car",
    ],
  },
  {
    slug: "privacy",
    label: "Privacy",
    color: "#6366F1",
    keywords: [
      "data privacy",
      "surveillance",
      "GDPR",
      "facial recognition",
      "tracking",
      "encryption",
      "privacy policy",
      "personal data",
      "right to be forgotten",
    ],
  },
  {
    slug: "conflict",
    label: "Conflict",
    color: "#B91C1C",
    keywords: [
      "war",
      "military",
      "troops",
      "airstrike",
      "ceasefire",
      "sanctions",
      "NATO",
      "invasion",
      "insurgent",
      "missile",
      "armed forces",
      "combat",
      "peacekeeping",
    ],
  },
  {
    slug: "regulation",
    label: "Regulation",
    color: "#7C3AED",
    keywords: [
      "antitrust",
      "legislation",
      "regulation",
      "FCC",
      "FTC",
      "EU Commission",
      "lawsuit",
      "compliance",
      "monopoly",
      "congressional hearing",
      "regulatory",
      "executive order",
    ],
  },
  {
    slug: "social-media",
    label: "Social Media",
    color: "#EC4899",
    keywords: [
      "TikTok",
      "Instagram",
      "Facebook",
      "Twitter",
      "YouTube",
      "Threads",
      "content moderation",
      "misinformation",
      "influencer",
      "Snapchat",
      "social network",
      "Meta",
    ],
  },
  {
    slug: "sports",
    label: "Sports",
    color: "#5856D6",
    keywords: [
      "NFL",
      "NBA",
      "FIFA",
      "MLB",
      "Olympics",
      "Premier League",
      "tennis",
      "World Cup",
      "championship",
      "playoff",
      "Super Bowl",
      "soccer",
      "football",
      "basketball",
      "baseball",
      "hockey",
      "NHL",
      "Grand Slam",
      "coach",
      "quarterback",
      "touchdown",
    ],
  },
  {
    slug: "entertainment",
    label: "Entertainment",
    color: "#F472B6",
    keywords: [
      "movie",
      "film",
      "streaming",
      "Netflix",
      "Disney",
      "Hollywood",
      "box office",
      "TV series",
      "album",
      "Grammy",
      "Oscar",
      "Emmy",
      "concert",
      "celebrity",
      "HBO",
      "Spotify",
      "Apple TV",
      "gaming",
      "video game",
    ],
  },
  {
    slug: "biotech",
    label: "Biotech",
    color: "#14B8A6",
    keywords: [
      "gene therapy",
      "CRISPR",
      "pharmaceutical",
      "clinical trial",
      "drug approval",
      "FDA",
      "biotech",
      "mRNA",
      "genomics",
      "vaccine",
      "antibody",
      "stem cell",
    ],
  },
  {
    slug: "apple",
    label: "Apple",
    color: "#A3AAAE",
    keywords: [
      "Apple",
      "iPhone",
      "iPad",
      "MacBook",
      "iMac",
      "Mac Pro",
      "Apple Watch",
      "AirPods",
      "Vision Pro",
      "iOS",
      "macOS",
      "watchOS",
      "App Store",
      "WWDC",
      "Tim Cook",
      "Apple Silicon",
      "M1",
      "M2",
      "M3",
      "M4",
    ],
  },
  {
    slug: "google",
    label: "Google",
    color: "#4285F4",
    keywords: [
      "Google",
      "Alphabet",
      "Android",
      "Chrome",
      "Pixel",
      "Google Cloud",
      "Google Maps",
      "Gmail",
      "Google Search",
      "Sundar Pichai",
      "DeepMind",
      "Waymo",
    ],
  },
  {
    slug: "microsoft",
    label: "Microsoft",
    color: "#00A4EF",
    keywords: [
      "Microsoft",
      "Windows",
      "Azure",
      "Office 365",
      "Xbox",
      "Surface",
      "Teams",
      "Bing",
      "LinkedIn",
      "GitHub",
      "Satya Nadella",
      ".NET",
      "Visual Studio",
    ],
  },
  {
    slug: "amazon",
    label: "Amazon",
    color: "#FF9900",
    keywords: [
      "Amazon",
      "AWS",
      "Alexa",
      "Prime",
      "Kindle",
      "Ring",
      "Amazon Web Services",
      "Andy Jassy",
      "Echo",
      "Fire TV",
      "Lambda",
      "S3",
    ],
  },
  {
    slug: "nvidia",
    label: "Nvidia",
    color: "#76B900",
    keywords: [
      "Nvidia",
      "GeForce",
      "CUDA",
      "RTX",
      "GPU",
      "Jensen Huang",
      "Tegra",
      "DGX",
      "H100",
      "A100",
      "Blackwell",
      "Grace Hopper",
    ],
  },
  {
    slug: "semiconductors",
    label: "Chips",
    color: "#0EA5E9",
    keywords: [
      "semiconductor",
      "chip",
      "TSMC",
      "Intel",
      "AMD",
      "Qualcomm",
      "Broadcom",
      "ARM",
      "nanometer",
      "foundry",
      "chipmaker",
      "processor",
      "CPU",
      "SoC",
      "fab",
      "CHIPS Act",
      "Samsung Foundry",
    ],
  },
  {
    slug: "cloud",
    label: "Cloud",
    color: "#0284C7",
    keywords: [
      "cloud computing",
      "SaaS",
      "PaaS",
      "IaaS",
      "serverless",
      "Kubernetes",
      "Docker",
      "microservices",
      "cloud migration",
      "multi-cloud",
      "hybrid cloud",
      "Snowflake",
      "Databricks",
      "Salesforce",
    ],
  },
  {
    slug: "smartphones",
    label: "Smartphones",
    color: "#E879F9",
    keywords: [
      "smartphone",
      "mobile phone",
      "5G",
      "foldable phone",
      "Samsung Galaxy",
      "OnePlus",
      "Xiaomi",
      "mobile app",
      "app update",
      "cellular",
      "handset",
    ],
  },
  {
    slug: "robotics",
    label: "Robotics",
    color: "#F97316",
    keywords: [
      "robot",
      "robotics",
      "autonomous",
      "drone",
      "Boston Dynamics",
      "humanoid robot",
      "industrial robot",
      "automation",
      "self-driving",
      "lidar",
      "autonomous vehicle",
    ],
  },
  {
    slug: "startups",
    label: "Startups",
    color: "#A855F7",
    keywords: [
      "startup",
      "venture capital",
      "seed round",
      "Series A",
      "Series B",
      "Y Combinator",
      "unicorn",
      "founder",
      "funding round",
      "accelerator",
      "incubator",
      "valuation",
    ],
  },
  {
    slug: "open-source",
    label: "Open Source",
    color: "#22C55E",
    keywords: [
      "open source",
      "open-source",
      "Linux",
      "Apache",
      "MIT license",
      "GPL",
      "GitHub repository",
      "contributor",
      "fork",
      "pull request",
      "maintainer",
    ],
  },
  {
    slug: "gaming",
    label: "Gaming",
    color: "#E11D48",
    keywords: [
      "PlayStation",
      "Nintendo",
      "Steam",
      "Valve",
      "Unreal Engine",
      "Unity",
      "esports",
      "game console",
      "Switch",
      "PS5",
      "game developer",
      "AAA game",
      "indie game",
    ],
  },
  {
    slug: "networking",
    label: "Networking",
    color: "#0891B2",
    keywords: [
      "Wi-Fi",
      "Bluetooth",
      "6G",
      "fiber optic",
      "broadband",
      "Cisco",
      "router",
      "network infrastructure",
      "Starlink",
      "ISP",
      "telecom",
      "Verizon",
      "AT&T",
      "T-Mobile",
    ],
  },
];

export const TAG_MAP = new Map<string, TagDefinition>(
  TAG_DEFINITIONS.map((t) => [t.slug, t])
);
