export type Keyword = string | { term: string; caseSensitive: boolean };

export interface TagDefinition {
  slug: string;
  label: string;
  color: string;
  keywords: Keyword[];
  parent?: string;
}

export const TAG_DEFINITIONS: TagDefinition[] = [
  {
    slug: "ai",
    label: "AI",
    color: "#8B5CF6",
    parent: "technology",
    keywords: [
      "artificial intelligence",
      "machine learning",
      "deep learning",
      "ChatGPT",
      "OpenAI",
      "large language model",
      "LLM",
      "generative ai",
      "neural network",
      "GPT",
      "Claude",
      "Gemini",
      "copilot",
    ],
  },
  {
    slug: "climate",
    label: "Climate",
    color: "#059669",
    parent: "science",
    keywords: [
      "climate change",
      "global warming",
      "carbon emissions",
      "renewable energy",
      "fossil fuel",
      "greenhouse gas",
      "net zero",
      "climate crisis",
      "sustainability",
    ],
  },
  {
    slug: "crypto",
    label: "Crypto",
    color: "#F59E0B",
    parent: "technology",
    keywords: [
      "cryptocurrency",
      "bitcoin",
      "ethereum",
      "blockchain",
      "crypto",
      "defi",
      "NFT",
      "web3",
      "stablecoin",
    ],
  },
  {
    slug: "cybersecurity",
    label: "Cybersecurity",
    color: "#EF4444",
    parent: "technology",
    keywords: [
      "cybersecurity",
      "data breach",
      "ransomware",
      "malware",
      "phishing",
      "hacking",
      "zero-day",
      "vulnerability",
      "cyber attack",
    ],
  },
  {
    slug: "space",
    label: "Space",
    color: "#3B82F6",
    parent: "science",
    keywords: [
      "NASA",
      "SpaceX",
      "satellite",
      "astronaut",
      { term: "Mars", caseSensitive: true },
      "lunar",
      "orbit",
      "rocket launch",
      "space station",
      "James Webb",
    ],
  },
  {
    slug: "election",
    label: "Election",
    color: "#DC2626",
    parent: "world",
    keywords: [
      "election",
      "voting",
      "ballot",
      "election campaign",
      "political candidate",
      "polling",
      "midterm",
      "presidential race",
      "electoral",
    ],
  },
  {
    slug: "economy",
    label: "Economy",
    color: "#0891B2",
    parent: "business",
    keywords: [
      "inflation",
      "recession",
      "interest rate",
      "federal reserve",
      "GDP",
      "unemployment",
      "stock market",
      "economic growth",
      "trade deficit",
      "tariff",
      "trade war",
      "layoffs",
      "IPO",
      "Wall Street",
      "central bank",
    ],
  },
  {
    slug: "health-crisis",
    label: "Health Crisis",
    color: "#E11D48",
    parent: "health",
    keywords: [
      "pandemic",
      "epidemic",
      "outbreak",
      "public health emergency",
      "bird flu",
      { term: "WHO", caseSensitive: true },
      "vaccine mandate",
      "quarantine",
    ],
  },
  {
    slug: "evs",
    label: "EVs",
    color: "#10B981",
    parent: "technology",
    keywords: [
      "electric vehicle",
      "EV",
      "Tesla",
      "charging station",
      "battery technology",
      "hybrid vehicle",
      "electric car",
    ],
  },
  {
    slug: "privacy",
    label: "Privacy",
    color: "#6366F1",
    parent: "technology",
    keywords: [
      "data privacy",
      "surveillance",
      "GDPR",
      "facial recognition",
      "tracking",
      "encryption",
      "privacy policy",
      "personal data",
      "right to be forgotten",
    ],
  },
  {
    slug: "conflict",
    label: "Conflict",
    color: "#B91C1C",
    parent: "world",
    keywords: [
      "war",
      "military",
      "troops",
      "airstrike",
      "ceasefire",
      "sanctions",
      "NATO",
      "invasion",
      "insurgent",
      "missile",
      "armed forces",
      "combat",
      "peacekeeping",
    ],
  },
  {
    slug: "regulation",
    label: "Regulation",
    color: "#7C3AED",
    parent: "world",
    keywords: [
      "antitrust",
      "legislation",
      "regulation",
      "FCC",
      "FTC",
      "EU Commission",
      "lawsuit",
      "compliance",
      "monopoly",
      "congressional hearing",
      "regulatory",
      "executive order",
    ],
  },
  {
    slug: "social-media",
    label: "Social Media",
    color: "#EC4899",
    parent: "technology",
    keywords: [
      "TikTok",
      "Instagram",
      "Facebook",
      "Twitter",
      "YouTube",
      { term: "Threads", caseSensitive: true },
      "content moderation",
      "misinformation",
      "influencer",
      "Snapchat",
      "social network",
      "Meta Platforms",
      "Mark Zuckerberg",
    ],
  },
  {
    slug: "sports",
    label: "Sports",
    color: "#5856D6",
    keywords: [
      "NFL",
      "NBA",
      "FIFA",
      "MLB",
      "Olympics",
      "Premier League",
      "tennis",
      "World Cup",
      "championship",
      "playoff",
      "Super Bowl",
      "soccer",
      "football",
      "basketball",
      "baseball",
      "hockey",
      "NHL",
      "Grand Slam",
      "coach",
      "quarterback",
      "touchdown",
    ],
  },
  {
    slug: "entertainment",
    label: "Entertainment",
    color: "#F472B6",
    keywords: [
      "movie",
      "film",
      "streaming service",
      "Netflix",
      "Disney",
      "Hollywood",
      "box office",
      "TV series",
      "album",
      "Grammy",
      "Oscar",
      "Emmy",
      "concert",
      "celebrity",
      "HBO",
      "Spotify",
      "Apple TV",
      "gaming",
      "video game",
    ],
  },
  {
    slug: "biotech",
    label: "Biotech",
    color: "#14B8A6",
    parent: "science",
    keywords: [
      "gene therapy",
      "CRISPR",
      "pharmaceutical",
      "clinical trial",
      "drug approval",
      "FDA",
      "biotech",
      "mRNA",
      "genomics",
      "vaccine",
      "antibody",
      "stem cell",
    ],
  },
  {
    slug: "apple",
    label: "Apple",
    color: "#A3AAAE",
    parent: "technology",
    keywords: [
      "Apple",
      "iPhone",
      "iPad",
      "MacBook",
      "iMac",
      "Mac Pro",
      "Apple Watch",
      "AirPods",
      "Vision Pro",
      "iOS",
      "macOS",
      "watchOS",
      "App Store",
      "WWDC",
      "Tim Cook",
      "Apple Silicon",
      "M1",
      "M2",
      "M3",
      "M4",
    ],
  },
  {
    slug: "google",
    label: "Google",
    color: "#4285F4",
    parent: "technology",
    keywords: [
      "Google",
      "Alphabet",
      "Android",
      "Chrome",
      "Pixel",
      "Google Cloud",
      "Google Maps",
      "Gmail",
      "Google Search",
      "Sundar Pichai",
      "DeepMind",
      "Waymo",
    ],
  },
  {
    slug: "microsoft",
    label: "Microsoft",
    color: "#00A4EF",
    parent: "technology",
    keywords: [
      "Microsoft",
      "Windows",
      "Azure",
      "Office 365",
      "Xbox",
      { term: "Surface", caseSensitive: true },
      "Microsoft Teams",
      { term: "Bing", caseSensitive: true },
      "LinkedIn",
      "GitHub",
      "Satya Nadella",
      ".NET",
      "Visual Studio",
    ],
  },
  {
    slug: "amazon",
    label: "Amazon",
    color: "#FF9900",
    parent: "technology",
    keywords: [
      "Amazon",
      "AWS",
      "Alexa",
      "Amazon Prime",
      "Prime Video",
      "Kindle",
      "Ring doorbell",
      "Amazon Web Services",
      "Andy Jassy",
      "Amazon Echo",
      "Fire TV",
      "Lambda",
      "S3",
    ],
  },
  {
    slug: "nvidia",
    label: "Nvidia",
    color: "#76B900",
    parent: "technology",
    keywords: [
      "Nvidia",
      "GeForce",
      "CUDA",
      "RTX",
      "GPU",
      "Jensen Huang",
      "Tegra",
      "DGX",
      "H100",
      "A100",
      "Blackwell",
      "Grace Hopper",
    ],
  },
  {
    slug: "semiconductors",
    label: "Chips",
    color: "#0EA5E9",
    parent: "technology",
    keywords: [
      "semiconductor",
      "chip",
      "TSMC",
      "Intel",
      "AMD",
      "Qualcomm",
      "Broadcom",
      "ARM",
      "nanometer",
      "foundry",
      "chipmaker",
      "processor",
      "CPU",
      "SoC",
      "fab",
      "CHIPS Act",
      "Samsung Foundry",
    ],
  },
  {
    slug: "cloud",
    label: "Cloud",
    color: "#0284C7",
    parent: "technology",
    keywords: [
      "cloud computing",
      "SaaS",
      "PaaS",
      "IaaS",
      "serverless",
      "Kubernetes",
      "Docker",
      "microservices",
      "cloud migration",
      "multi-cloud",
      "hybrid cloud",
      "Snowflake",
      "Databricks",
      "Salesforce",
    ],
  },
  {
    slug: "smartphones",
    label: "Smartphones",
    color: "#E879F9",
    parent: "technology",
    keywords: [
      "smartphone",
      "mobile phone",
      "5G",
      "foldable phone",
      "Samsung Galaxy",
      "OnePlus",
      "Xiaomi",
      "mobile app",
      "app update",
      "cellular",
      "handset",
    ],
  },
  {
    slug: "robotics",
    label: "Robotics",
    color: "#F97316",
    parent: "technology",
    keywords: [
      "robot",
      "robotics",
      "autonomous robot",
      "drone strike",
      "delivery drone",
      "Boston Dynamics",
      "humanoid robot",
      "industrial robot",
      "automation",
      "self-driving",
      "lidar",
      "autonomous vehicle",
    ],
  },
  {
    slug: "startups",
    label: "Startups",
    color: "#A855F7",
    parent: "business",
    keywords: [
      "startup",
      "venture capital",
      "seed round",
      "Series A",
      "Series B",
      "Y Combinator",
      "unicorn",
      "co-founder",
      "funding round",
      "accelerator",
      "incubator",
      "valuation",
    ],
  },
  {
    slug: "open-source",
    label: "Open Source",
    color: "#22C55E",
    parent: "technology",
    keywords: [
      "open source",
      "open-source",
      "Linux",
      "Apache",
      "MIT license",
      "GPL",
      "GitHub repository",
      "open source contributor",
      "pull request",
    ],
  },
  {
    slug: "gaming",
    label: "Gaming",
    color: "#E11D48",
    parent: "entertainment",
    keywords: [
      "PlayStation",
      "Nintendo",
      { term: "Steam", caseSensitive: true },
      { term: "Valve", caseSensitive: true },
      "Unreal Engine",
      { term: "Unity", caseSensitive: true },
      "esports",
      "game console",
      "Nintendo Switch",
      "PS5",
      "game developer",
      "AAA game",
      "indie game",
    ],
  },
  {
    slug: "networking",
    label: "Networking",
    color: "#0891B2",
    parent: "technology",
    keywords: [
      "Wi-Fi",
      "Bluetooth",
      "6G",
      "fiber optic",
      "broadband",
      "Cisco",
      "router",
      "network infrastructure",
      "Starlink",
      "ISP",
      "telecom",
      "Verizon",
      "AT&T",
      "T-Mobile",
    ],
  },
  {
    slug: "technology",
    label: "Technology",
    color: "#007AFF",
    keywords: [
      "tech",
      "software",
      "hardware",
      "gadget",
      "computer",
      "internet",
      "digital",
      "Silicon Valley",
      "programmer",
      "developer",
      "algorithm",
      "data center",
      "cybersecurity",
      "startup",
    ],
  },
  {
    slug: "business",
    label: "Business",
    color: "#34C759",
    keywords: [
      "business",
      "corporation",
      "CEO",
      "revenue",
      "profit",
      "merger",
      "acquisition",
      "earnings",
      "shareholder",
      "quarterly results",
      "market cap",
      "supply chain",
      "enterprise",
      "Fortune 500",
    ],
  },
  {
    slug: "science",
    label: "Science",
    color: "#AF52DE",
    keywords: [
      "science",
      "scientist",
      "scientific research",
      "scientific study",
      "experiment",
      "discovery",
      "physics",
      "chemistry",
      "biology",
      "astronomy",
      "evolution",
      "laboratory",
      "peer review",
    ],
  },
  {
    slug: "world",
    label: "World",
    color: "#FF9500",
    keywords: [
      "geopolitics",
      "diplomacy",
      "United Nations",
      "foreign policy",
      "summit",
      "treaty",
      "ambassador",
      "refugee",
      "humanitarian",
      "international relations",
      "global affairs",
      "bilateral",
      "G7",
      "G20",
    ],
  },
  {
    slug: "health",
    label: "Health",
    color: "#00C7BE",
    keywords: [
      "health",
      "medical",
      "doctor",
      "hospital",
      "patient",
      "treatment",
      "diagnosis",
      "surgery",
      "therapy",
      "wellness",
      "nutrition",
      "mental health",
      "disease",
      "medication",
      "healthcare",
    ],
  },
];

export const TAG_MAP = new Map<string, TagDefinition>(
  TAG_DEFINITIONS.map((t) => [t.slug, t])
);
